# Generated by Django 3.2.5 on 2021-08-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fc_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='fcuser',
            name='useremail',
            field=models.CharField(default='test.com', max_length=128, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
